### ISSUE TITLE
bitcode error when Archiving

### ISSUE THREAD

**Issue by basiralam** [jinht/FloatingBall#2]
hi,
I am using your control and when I am trying to archive the project I am getting the following error.

ld: bitcode bundle could not be generated because '/Users/myMac/iOS Project/myApp/JhtFloatingBallSDK/JhtFloatingBallSDK.a(JhtFloatingBall.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

**Comment by jinht** [comment]
@basiralam https://github.com/jinht/DocViewer/issues/1
