### ISSUE TITLE
停靠限制不够友好，我想只是停靠右边或者左边无法满足

### ISSUE THREAD

**Issue by LinKeymy** [jinht/FloatingBall#4]
// 停靠方式
typedef NS_ENUM(NSInteger, Jht_StayMode) {
    // 四周均可停靠（优先考虑左右两侧，具体处理逻辑同AssistiveTouch）
    stayMode_Around = 0,
    // 只能停靠左右两侧
    stayMode_OnlyLeftAndRight = 1
};

请求提供单边停靠，左边 ModeLeft 后边 Modright 两边的话 ModeLeft | Modright ，谢谢，😄，或者给出源码我自己改改也好

**Comment by jinht** [comment]
@LinKeymy 已做更新

**Comment by LinKeymy** [comment]
谢谢
