### ISSUE TITLE
停靠以后复位

### ISSUE THREAD

**Issue by KieSun** [jinht/FloatingBall#5]
页面是可滑动的，按钮拖动停靠以后马上就回到原位了，这是什么问题

**Comment by KieSun** [comment]
问题解决了 必须使用 frame 的方式，我之前使用了自动布局。还有个问题，是否可以暴露一下图片的填充方式 API

**Comment by jinht** [comment]
@KieSun 具体点

**Comment by KieSun** [comment]
使用 autolayout 布局 FloatingBall 的话，我这里会出现拖动 ball 以后自动回到原本位置的问题。还有是否可以提供图片的 contentModel API，不希望按比例拉伸图片

**Comment by jinht** [comment]
@KieSun contentMode 还怎么给你提供API呢？
